
service: profile-api


 

plugins:
  - serverless-offline




provider:
  name: aws
  runtime: nodejs12.x
     

functions:
  createProfile:
    handler: api/createProfile.handler
    description: CREATES a new profile
    events:
      - http:
          path: profiles
          method: post
          cors:
            origin: '*'
  getProfiles:
      handler: api/getNotes.handler
      description: Gets all the profiles
      events:
          - http:
              path: profiles
              method: get            
              cors:
                  origin: '*'
  updateProfile:
      handler: api/UpdateProfile.handler
      description: updates a single profile
      events:
            - http:
                path: profiles/{id}
                method: put 
                cors:
                    origin: '*'
  deleteProfile:
      handler: api/deleteProfile.handler
      description: deletes a profile
      events:
          - http:
              path: profiles/{id}
              method: delete
              cors: 
                origin: '*'
  getProfile:
      handler: api/getProfile.handler
      description: gets a single profile
      events:
          - http:
              path: profiles/{id}    
              method: get
              cors:
                  origin: '*'
                  