
service: profile-api


 

plugins:
  - serverless-offline




provider:
  name: aws
  runtime: nodejs12.x

     *

functions:
  createProfile:
    handler: api/createProfile.handler
    description: CREATES a new profile
    events:
      - http:
          path: profiles/
          method: post
          cors:
            origin: '*'

