
service: profile-api


 

plugins:
  - serverless-offline




provider:
  name: aws
  runtime: nodejs12.x
     

functions:
  createProfile:
    handler: api/createProfile.handler
    description: CREATES a new profile
    events:
      - http:
          path: profiles
          method: post
          cors:
            origin: '*'
  getProfiles:
      handler: api/getNotes.handler
      description: Gets all the profiles
      events:
          - http:
              path: profiles
              method: get            
              cors:
                  origin: '*'